"use client";
import "./globals.css";
import { Inter } from "next/font/google";
import { ThirdwebProvider } from "@thirdweb-dev/react";
import { BinanceTestnet, Mumbai } from "@thirdweb-dev/chains";

const inter = Inter({ subsets: ["latin"] });

const activeChain = "binance-testnet";

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  return (
    <ThirdwebProvider
      activeChain={activeChain}
      supportedChains={[BinanceTestnet, Mumbai]}
    >
      <html lang="en">
        <body className={inter.className}>{children}</body>
      </html>
    </ThirdwebProvider>
  );
}
